apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipam4lab-data
  labels:
    app: ipam4lab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""  # Use default storage class
